    [project]
    name = "financiero"
    version = "0.1.0"
    description = "Atención a Domicilio de Electricistas"
    requires-python = ">=3.12"
    dependencies = [
       "WhatsApp"        
    ]
    [dependency-groups]
    dev = ["workers-py"]
